### ISSUE TITLE
glyph-icons are showing up as rectangles

### ISSUE THREAD

**Issue by cvandermeer** [twbs/bootstrap-sass#925] opened 2015-06-22 09:32 UTC
I am using bootstrap-sass 3.3.3.
The glyphicons are showing up as square rectangles []
I have no errors when i inspect element

application.scss
@import "bootstrap-sprockets";
@import "bootstrap";

application.js
//= require bootstrap-sprockets

**Comment by Kelvin-09** [comment] 2015-06-23 02:17
I have the same error.
I checked the complied code, and find that the definition of font-face(Glyphicons Halflings) is surrounding by at-root tag.
Is it the problem of sass?

My bootstrap-sass version: 3.3.5.
My sass version: 3.4.15.

**Comment by Kelvin-09** [comment] 2015-06-23 02:22
Delete the surrounding at-root tag in assets/stylesheets/bootstrap/_glyphicons.scss can solve this problem.

**Comment by organicweb** [comment] 2015-06-23 09:07
Deleting at-root worked for me !

**Comment by cvrebert** [comment] 2015-06-23 18:11
I can't repro with Sass 3.4.15 (Selective Steve); there's no `@at-root` in the output.
bootstrap-sass now requires Sass >=3.3.x. See #920.

@Kelvin-09 Can you please triple-check that you're using the right versions of Sass and bootstrap-sass?

**Comment by Kelvin-09** [comment] 2015-06-23 18:32
Thank you, @cvrebert .
I just complied the source code with sass, and the at-root was disappeared this time.
But when I'm using grunt and grunt-sass to complie the source code, the problem happens again.
I think there's something goes wrong in my grunt configuration file.

**Comment by cvrebert** [comment] 2015-06-23 18:35
@cvandermeer What version of Sass are you using?

**Comment by cvandermeer** [comment] 2015-06-23 18:38
I was using sass-rails 4.0.3

**Comment by Kelvin-09** [comment] 2015-06-23 18:40
Oh, I get it.
The version of my Sass and bootstrap-sass are both the latest.
But I forget to update grunt-sass from 0.14.0 to 1.0.0.
Hope this can help you, @cvandermeer .

**Comment by cvrebert** [comment] 2015-06-23 19:00
@cvandermeer Looks like that depends on sass `~> 3.1`. Can you check what actual version of Sass you have installed?

**Comment by cvandermeer** [comment] 2015-06-23 19:28
AH Its 3.2 So that might be the issue

**Comment by cvrebert** [comment] 2015-06-23 19:34
Ok, closing this as a duplicate of #920 then.

**Closed by cvrebert** 2015-06-23 19:34 UTC

**Comment by cvandermeer** [comment] 2015-06-24 10:27
Updating sass fixed it!

**Comment by cvrebert** [comment] 2015-06-24 10:52
Great!
