### ISSUE TITLE
glyphicons 404 not loading after removing and copying font files

### ISSUE THREAD

**Issue by lustremedia** [twbs/bootstrap-sass#931] opened 2015-06-30 22:18 UTC
Glyphicons were working no problem using the Readme _b. Compass_ rails-sass gem setup. After accidentally removing the font/bootstrap/\* files the browser presents me with 404 errors on the .woff, woff2 and the ttf files.

My git diff on the generated _style.css_ shows following:

```
@font-face {
   font-family: 'Glyphicons Halflings';
-  src: url(../fonts/bootstrap/glyphicons-halflings-regular.eot?1435571832);
-  src: url(../fonts/bootstrap/glyphicons-halflings-regular.eot?&1435571832#iefix) format("embedded-opentype"), url(../fonts/bootstrap/glyphicons-halflings-regular.woff2?1435571832) format("woff2"), url(../fonts/bootstrap/g
+  src: url(/fonts/bootstrap/glyphicons-halflings-regular.eot?1435701655);
+  src: url(/fonts/bootstrap/glyphicons-halflings-regular.eot?&1435701655#iefix) format("embedded-opentype"), url(/fonts/bootstrap/glyphicons-halflings-regular.woff2?1435701655) format("woff2"), url(/fonts/bootstrap/glyphic
 }
```

Why has the font url changed from an relative to an absolute url?

**Comment by cvrebert** [comment] 2015-07-01 07:18
Duplicate of #875 perhaps?

**Comment by glebm** [comment] 2015-07-01 10:32
The URL for the Rails version has always been absolute.
Please post your version of Rails, sass-rails, sprockets, configuration, and how you import bootstrap.

**Comment by jpatel531** [comment] 2015-07-01 14:49
Probably won't be useful to anyone else - but I was on the latest version of bootstrap, sass-rails - but glyphicons 404d. Updating sprockets worked

**Comment by lustremedia** [comment] 2015-07-01 21:05
Hi @glebm
I am not using Rails I use the compass sass-rails setup as described in the readme in b. Compass without Rails with the latest gems.

Bundle gives me follwing:

Using rake (10.4.2)
Using addressable (2.3.8)
Using execjs (2.5.2)
Using json (1.8.3)
Using autoprefixer-rails (5.2.1)
Using sass (3.4.15)
Using bootstrap-sass (3.3.5.1)
Using i18n (0.7.0)
Using colorize (0.7.7)
Using net-ssh (2.9.2)
Using net-scp (1.2.1)
Using sshkit (1.7.1)
Using capistrano (3.4.0)
Using chunky_png (1.3.4)
Using multi_json (1.11.1)
Using compass-core (1.0.3)
Using compass-import-once (1.0.5)
Using rb-fsevent (0.9.5)
Using ffi (1.9.9)
Using rb-inotify (0.9.5)
Using compass (1.0.3)
Using css_parser (1.3.6)
Using bundler (1.5.2)

**Comment by glebm** [comment] 2015-07-01 21:07
Note that when using compass the font files must be copied into the project. Also, what does your main scss file look like?

**Comment by lustremedia** [comment] 2015-07-01 21:12
hi @glebm 
I changed 
```
$icon-font-path: "../fonts/bootstrap/"
```

I get ```/font/../font/bootstrap```

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url(/fonts/../fonts/bootstrap/glyphicons-halflings-regular.eot?1435701655);
  src: url(/fonts/../fonts/bootstrap/glyphicons-halflings-regular.eot?&1435701655#iefix) format("embedded-opentype"), url(/fonts/../fonts/bootstrap/glyphicons-halflings-regular.woff2?1435701655) format("woff2"), url(/fonts/../fonts/bootstrap/glyphicons-halflings-regular.woff?1435701655) format("woff"), url(/fonts/../fonts/bootstrap/glyphicons-halflings-regular.ttf?1435701655) format("truetype"), url(/fonts/../fonts/bootstrap/glyphicons-halflings-regular.svg?1435701655#glyphicons_halflingsregular) format("svg");
}
```

Main scss file looks like this:
```
// Import Bootstrap Compass integration
@import "bootstrap-compass";

// Import custom Bootstrap variables
@import "bootstrap-variables";

// Import Bootstrap for Sass
@import "bootstrap";


@import "variables-site/variables-site";
@import "mixins/mixins-master";

/*--------------------------------------------------------------
# Typography
--------------------------------------------------------------*/
@import "typography/typography";

/*--------------------------------------------------------------
# Elements
--------------------------------------------------------------*/
@import "elements/elements";

/*--------------------------------------------------------------
# Forms
--------------------------------------------------------------*/
/// @import "forms/forms";

/*--------------------------------------------------------------
# Navigation
--------------------------------------------------------------*/
@import "navigation/navigation";

/*--------------------------------------------------------------
# Accessibility
--------------------------------------------------------------*/
// @import "modules/accessibility";

/*--------------------------------------------------------------
# Alignments
--------------------------------------------------------------*/
// @import "modules/alignments";

/*--------------------------------------------------------------
# Widgets
--------------------------------------------------------------*/
@import "site/secondary/widgets";

/*--------------------------------------------------------------
# Content
--------------------------------------------------------------*/
@import "site/site";

/*--------------------------------------------------------------
# Infinite scroll
--------------------------------------------------------------*/
// @import "modules/infinite-scroll";

/*--------------------------------------------------------------
# Media
--------------------------------------------------------------*/
// @import "media/media";

@import 'rtl';
```

fonts are in the project!

**Comment by lustremedia** [comment] 2015-07-01 21:43
@glebm like I said, all was working well until I deleted the glyphicon files and recopied them into the project.

**Comment by lustremedia** [comment] 2015-07-01 21:49
Ok what seems to get me back on track is adding following:
```
$bootstrap-sass-asset-helper: false;
$icon-font-path: "../fonts/bootstrap/";
```

In the _bootstrap-variables.scss as @simongcc suggests in #875 via @cvrebert so the issue seems to be related to #875.

**Comment by lustremedia** [comment] 2015-07-01 21:53
If that is the way to deal with fonts, maybe it should go up on the Readme file under Compass. If that is a workaround and something needs to be fixed let me know and I can provide the data needed.

**Closed** 2018-08-21 22:12 UTC
