### ISSUE TITLE
bower.json should restrict to jquery < 3?

### ISSUE THREAD

**Issue by cjerdonek** [twbs/bootstrap-sass#1041] opened 2016-06-09 20:17 UTC
This issue is to suggest restricting jquery to < 3 in bower.json.  Currently (as of 3.3.6), Bootstrap's bower.json says this (from [here](https://github.com/twbs/bootstrap/blob/v3.3.6/bower.json#L32)):

    "jquery": "1.9.1 - 2"

But this project's bower.json says this:

    "jquery": ">= 1.9.0"

The user will get an error like the following at runtime if jquery 3 winds up getting installed: "Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3"

**Comment by cvrebert** [comment] 2016-06-10 07:10
Duplicate of #1042.

**Closed by cvrebert** 2016-06-10 07:10 UTC
Labels: bug
