### ISSUE TITLE
hgroup tag is deprecated

### ISSUE THREAD

**Issue by misterfresh** [twbs/bootstrap-sass#880] opened 2015-04-05 19:38 UTC
Line 40 in "assets/stylesheets/bootstrap/_normalize.scss"
The hgroup tag is deprecated and therefore shows up as an error in IDE.
It can be removed.

**Comment by cvrebert** [comment] 2015-04-07 04:49
Duplicate of https://github.com/necolas/normalize.css/pull/394

**Closed by cvrebert** 2015-04-07 04:49 UTC
