### ISSUE TITLE
Rails 5 alpha: valid_asset_uri?': undefined methodstart_with?' for #Regexp

### ISSUE THREAD

**Issue by chasik** [twbs/bootstrap-sass#960] opened 2015-09-03 08:37 UTC
With run server (rails s) get error: gems/sprockets-7b913165d54b/lib/sprockets/uri_utils.rb:75:in `valid_asset_uri?': undefined method `start_with?' for #<Regexp:0x00000006e76228> (NoMethodError)

valid_asset_uri? waiting string but gets rexexp from engine.rb:8

app.config.assets.precompile << %r(bootstrap/glyphicons-halflings-regular\.(?:eot|svg|ttf|woff2?)$)

**Comment by chasik** [comment] 2015-09-03 10:42
I do not know the reason ... To get rid of the errors connected https://github.com/twbs/bootstrap-rubygem - everything works well ...

**Comment by tjgrathwell** [comment] 2015-09-22 06:26
The cause of the error seems to be [this line](https://github.com/twbs/bootstrap-sass/blob/3e33c6f0d7745cb6956d8d09281e729c2a48f072/lib/bootstrap-sass/engine.rb#L8) which adds `%r(bootstrap/glyphicons-halflings-regular\.(?:eot|svg|ttf|woff2?)$)` to the assets precompile path.

At some point in the transition to Sprockets 4 adding a RegExp to the precompile list has started crashing.

**Comment by tjgrathwell** [comment] 2015-09-22 18:42
Apparently passing a regexp into 'precompile' is deprecated.

Relevant issues are https://github.com/rails/sprockets/issues/117 (sprockets) and https://github.com/rails/sprockets-rails/issues/269 (sprockets-rails)

It looks like this will be fixed in `bootstrap-sass` if #965 is accepted

**Comment by glebm** [comment] 2015-09-27 12:54
Merged the PR and now testing with Rails HEAD.

**Closed by glebm** 2015-09-27 12:54 UTC
