### ISSUE TITLE
Glyphicons seem to be broken

### ISSUE THREAD

**Issue by ntopulos** [twbs/bootstrap-sass#1032] opened 2016-04-25 12:26 UTC
There seems to be an issue with the fonts provided in your package.
I created a new project using Compass:

    $ compass create my-new-project -r bootstrap-sass --using bootstrap

Then I copied the font folder to the public directory and the Glyphicons would not work. They were loaded by the browser with the correct HTTP header type, but would not show up.
To fix it, I simply downloaded the [classic version](https://github.com/twbs/bootstrap/releases/download/v3.3.6/bootstrap-3.3.6-dist.zip) of Bootstrap and replaced all my font files in the public directory by those from this zip.

**Comment by lumineida** [comment] 2016-04-29 19:09
I had the same issue. @ntopulos thank you! You've saved my day :-)

**Comment by nato522** [comment] 2016-05-10 11:01
I had that same issue but your fix didn't work for me :(
I'm using Glyphicons separately, directly referencing them on Bootstrap CDN.
`<link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">`

**Comment by cvrebert** [comment] 2016-06-10 07:20
Duplicate of #875 or #932 perhaps?

> To fix it, I simply downloaded the classic version of Bootstrap and replaced all my font files in the public directory by those from this zip.

That makes no sense. The two sets of files are bit-for-bit identical. I just rechecked the SHA-1 hashes.

**Comment by glebm** [comment] 2016-06-10 07:26
Just rechecked the file permissions @v3.3.6, but they're correct too (`-rw-rw-r--`).

**Comment by ntopulos** [comment] 2016-06-10 08:25
Ok, I just did the test again and the icons downloaded by compass are definitely not the same as those provided in the classic version:

File                              | compass | classic |
----------------------------------|---------|---------|
glyphicons-halflings-regular.eot  |    1 KB |   20 KB |
glyphicons-halflings-regular.svg  |  107 KB |  107 KB |
glyphicons-halflings-regular.ttf  |    2 KB |   45 KB |
glyphicons-halflings-regular.woff |    1 KB |   23 KB |
glyphicons-halflings-regular.woff2|    1 KB |   18 KB |

I doubt it has something to do with #875.  
Here is the software I used: `v3.3.6`, `ruby 2.2.4p230`, `Compass 1.0.3 (Polaris)` and `Sass 3.4.21 (Selective Steve)`.

**Comment by cvrebert** [comment] 2016-06-10 09:03
I'm unable to reproduce. Same versions, except I have `ruby 2.3.1p112`.
Perhaps your copy of the gem got borked? Try uninstalling the `bootstrap-sass` gem and then reinstalling it.

**Comment by hallaathrad** [comment] 2016-06-22 02:32
On my project, we've had the same issue and @nato522's solution does it. Perhaps we can find an offline-friendly solution?

**Comment by cvrebert** [comment] 2016-06-22 02:41
That's pretty hard to do when we can't reproduce the problem in the first place...
Could you post a ZIP of the font files that Compass downloaded? Maybe we'll find some clue in the content of the bad files.

**Comment by hallaathrad** [comment] 2016-06-22 02:56
Perhaps it's fair to say I should've been more specific/clear. We haven't used compass, and the files do seem to have the right sizes... yet somehow the path simply doesn't match. (funny enough, the browser can see the files and show a preview and all). 
<img width="1337" alt="screen shot 2016-06-21 at 22 53 28" src="https://cloud.githubusercontent.com/assets/2107110/16253269/286f5d4c-3803-11e6-8167-ae87736f876c.png">
And we've installed the gem through `gem install`, not using compass.

**Comment by cvrebert** [comment] 2016-06-24 06:45
If you're not using any tooling, you may need to manually adjust the variables mentioned in https://github.com/twbs/bootstrap-sass#fonts

**Comment by Arugin** [comment] 2016-07-28 10:23
Any updates?

**Comment by cvrebert** [comment] 2016-08-29 21:02
Closing as not reproducible.

**Closed by cvrebert** 2016-08-29 21:02 UTC
