### ISSUE TITLE
.modal-backdrop is not appearing because _modals.scss is missing "bottom: 0"

### ISSUE THREAD

**Issue by mpiasta-ca** [twbs/bootstrap-sass#865] opened 2015-03-12 17:28 UTC
Currently, when using the modal window, it is missing the black backdrop. For some reason, `.modal-backdrop` in `assets/stylesheets/bootstrap/_modals.scss` is missing `bottom: 0;` on line 69.

```
// Modal background
.modal-backdrop {
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  background-color: $modal-backdrop-bg;
  // Fade for backdrop
  &.fade { @include opacity(0); }
  &.in { @include opacity($modal-backdrop-opacity); }
}
```

**Comment by cvrebert** [comment] 2015-03-13 14:36
A. Substantive stylesheet bugs not caused by the Less=>Sass translation process itself should be reported upstream to https://github.com/twbs/bootstrap
B. Fixed by https://github.com/twbs/bootstrap/pull/15881 . Please wait for the next release.

**Closed by cvrebert** 2015-03-13 14:36 UTC
