### ISSUE TITLE
Breadcrumbs broken between 3.3.1 and 3.3.3

### ISSUE THREAD

**Issue by FranzZemen** [twbs/bootstrap-sass#833] opened 2015-01-22 15:48 UTC
The separator disappeared.  Reverted and it worked.

**Comment by cvrebert** [comment] 2015-01-30 07:04
Have you tried clearing the cache? (`rm -rf tmp/cache`)

**Comment by julzmon** [comment] 2015-01-30 20:31
I'm having the same issue. Clearing cache didn't help.

**Comment by cvrebert** [comment] 2015-01-30 20:38
Are you using libsass/node-sass, or Ruby Sass?

**Comment by FranzZemen** [comment] 2015-02-03 05:46
Ruby Sass

**Comment by shawnacscott** [comment] 2015-02-04 19:23
Can't reproduce this on my Rails project. It works on Firefox and Chrome on OSX 10.10.1 for me.

**Comment by glebm** [comment] 2015-02-23 20:04
If anyone can reproduce this, please post a demo app on Github.

**Comment by andrewmbacon** [comment] 2015-02-28 17:59
Output is missing quotations marks around the content property. 

![image](https://cloud.githubusercontent.com/assets/5542706/6427245/922a1012-bf49-11e4-98ec-8e24f89d3aa5.png)

**Comment by glebm** [comment] 2015-02-28 19:36
@andrewmbacon Versions of bootstrap-sass and sass?

**Comment by andrewmbacon** [comment] 2015-02-28 21:23
@glebm Not sure how to find what version of Sass I'm running, but the download was bootstrap-sass-3.3.2

**Comment by andrewmbacon** [comment] 2015-02-28 21:28
@glebm Sass 3.4.5 ... will update Sass and see if that fixes it.

**Comment by andrewmbacon** [comment] 2015-02-28 21:55
@glebm Updated my Sass to 3.4.13, no effect. 

Output remains: 

![image](https://cloud.githubusercontent.com/assets/5542706/6428294/86fd814e-bf6a-11e4-9abc-2a226118a6c4.png)

**Comment by glebm** [comment] 2015-02-28 22:17
This bug is fixed in bootstrap-sass 3.3.3, please upgrade.

**Closed** 2015-02-28 22:17 UTC
