### ISSUE TITLE
Bug Report: Boostrap SASS Installation

### ISSUE THREAD

**Issue by jgacuca567** [twbs/bootstrap-sass#1057] opened 2016-07-21 15:00 UTC
After Installing `bootstrap-sass` using `npm`, this is the error that I get below. Looks like the issue was never resolved according to issue #18368. 

<img width="1137" alt="screen shot 2016-07-21 at 10 39 30 am" src="https://cloud.githubusercontent.com/assets/4000076/17027053/60ae870c-4f30-11e6-96ab-42ed490da9c2.png">

**Comment by cvrebert** [comment] 2016-07-21 16:03
What version of bootstrap-sass are you using?

**Comment by jgacuca567** [comment] 2016-07-21 16:32
@cvrebert Version `3.3.6`

**Comment by bsssshhhhhhh** [comment] 2016-07-21 19:23
@jgacuca567 
I just had this issue as well. Turns out there were some variables being accidentally overwritten before the bootstrap import. Moving `@import "bootstrap";` up a few lines solved my issue.

See #750

**Comment by jgacuca567** [comment] 2016-07-21 21:53
@bsssshhhhhhh, could you post a screenshot, so I can see where the 
```css 
@import 'bootstrap'; 
``` 
file is located

**Comment by cvrebert** [comment] 2016-07-22 04:40
Unable to reproduce.
Assuming this is a duplicate of #750.

**Closed by cvrebert** 2016-07-22 04:40 UTC
Labels: bug

**Comment by jgacuca567** [comment] 2016-07-23 01:38
@cvrebert are you using `grunt`, how was your style.scss setup?

**Comment by bsssshhhhhhh** [comment] 2016-07-23 01:45
@jgacuca567 It would help if you told us how your style.scss is set up. If you're overriding any of bootstrap's variables, make sure the units are the same as they are by default. Not really sure what else to tell you without seeing your scss files.

**Comment by jgacuca567** [comment] 2016-07-23 20:08
@bsssshhhhhhh @cvrebert , attached is my `style.scss` and `gruntfile.js` below. Let me know whats missing. I did not override anything, the installation was as is. 

[See Gist File ](https://gist.github.com/jgacuca567/dc2f1ab0664a58a35fa62f4cda190265)

See Image of my includes folder 
<img width="260" alt="screen shot 2016-07-23 at 4 06 40 pm" src="https://cloud.githubusercontent.com/assets/4000076/17080027/9f18000c-50ef-11e6-92fc-301a03329bb9.png">

**Comment by cvrebert** [comment] 2016-07-23 20:26
> are you using grunt, how was your style.scss setup

No, I simply ran `sass node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss`

**Comment by jgacuca567** [comment] 2016-07-23 21:02
@cvrebert That prints the stylesheet in the terminal. How are you setting up your gruntfile and style.scss? Post your demo.

**Comment by cvrebert** [comment] 2016-07-23 22:27
That was the entirety of my demo. The point was to demonstrate that the bug does not lie with bootstrap-sass itself. It must lie with your particular styles or build, which puts it beyond the scope of this issue tracker.

Presumably your `'includes/variables'` assigns one of the variables to a value with an incompatible unit. Check the variables referenced in the error message.

**Comment by jgacuca567** [comment] 2016-07-23 23:26
@cvrebert, I recopied the variables page and found what was going wrong, a minor error on my end. Thank you for being patient. The issue is fully resolved.
